import Head from "next/head";
import "reset-css";
import Image from "next/image";
import placeholder from "../images/placeholder.webp";
import { useEffect, useState } from "react";
function Listing({ id }: { id: string }) {
  const [profile, setProfile] = useState<{
    country: string;
    logo: string;
    name: string;
  } | null>(null);
  const [quote, setQuote] = useState({
    current: 0,
    high: 0,
    low: 0,
    open: 0,
    close: 0,
  });
  async function getCompanyProfile(id: string) {
    const queryParams = new URLSearchParams({
      symbol: id,
    });
    const res = await fetch(`/api/profile?${queryParams}`);
    if (res.ok) {
      const jsonData = await res.json();
      setProfile(jsonData);
    }
  }
  async function getQuote(id: string) {
    const queryParams = new URLSearchParams({
      symbol: id,
    });
    const res = await fetch(`/api/quote?${queryParams}`);
    if (res.ok) {
      const jsonData = await res.json();
      const { c, h, l, o, pc } = jsonData;
      setQuote({ current: c, high: h, low: l, open: o, close: pc });
    }
  }
  useEffect(() => {
    getCompanyProfile(id);
    getQuote(id);
  }, []);
  return profile ? (
    <div className="w-full rounded-md p-5 bg-slate-400 flex mb-5">
      <div>
        <Image
          height={120}
          width={120}
          src={profile.logo ? profile.logo : placeholder}
          alt="company logo"
        />
      </div>
      <div className="ml-5">
        <span className="block text-xl">{profile.name}</span>
        <span className="block text-xl">{id}</span>
        <span className="block text-3xl">${quote.current}</span>
      </div>
    </div>
  ) : (
    <span>loading</span>
  );
}
export default function Favorites() {
  const [favorites, setFavorite]: [string[], any] = useState([]);
  useEffect(() => {
    const favorites = localStorage.getItem("favorite");
    console.log(favorites);
    if (favorites) {
      const favoritesJson = JSON.parse(favorites);
      setFavorite(favoritesJson.items);
      console.log(favoritesJson.items);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="max-w-xl m-auto">
          <div className="w-full h-28 bg-red-300 mt-28">
            <span className="block text-center text-2xl mb-3">Favorites</span>
            {favorites.length ? (
              favorites.map((e) => <Listing key={e} id={e} />)
            ) : (
              <h1>no favorites</h1>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
